index:
    path: /
    controller: App\Controller\LuckyController::index

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
blog_list:
    path: /blog
    controller: App\Controller\BlogController::index
blog_show:
    path: /blog/{slug}
    controller: App\Controller\BlogController:show
about_us:
    path:
      ru: /o-nas/
      en: /about-us/
    controller: App\Controller\CompanyController::about